// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopsicleFactoryCo.Data;

#nullable disable

namespace PopsicleFactoryCo.Migrations
{
    [DbContext(typeof(PopsicleDBContext))]
    [Migration("20260113003821_CreateEFCoreDB1")]
    partial class CreateEFCoreDB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PopsicleFactoryCo.Models.PopsicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Flavour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Popsicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Flavour = "Chocolate",
                            Name = "Nicollete path hole",
                            Price = 15,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Flavour = "Vanilla",
                            Name = "Durham style",
                            Price = 10,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Flavour = "Strawberry",
                            Name = "Duval style",
                            Price = 20,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Flavour = "Orange",
                            Name = "Deccan style",
                            Price = 25,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Flavour = "Blueberry",
                            Name = "Boulevard style",
                            Price = 20,
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
